server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#false here means 👉 "I am the boss registry — I neither register myself, nor fetch from others."